### PR TITLE
Making Lantz a namespace package.

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This makes lantz a namespace package. And core one contribution. If this PR is accepted the repo should be renamed lantz.core

### CODE REVIEW

**Comment by alexforencich** [comment]
I was wondering if something like this was possible.  I am all for doing this as long as there are no issues with package management as it's significantly cleaner than lantz_core/lantz_drivers.  Are you sure this will work with pip as well as with system-level package managers (dpkg, yum, pacman, etc.)?

**Comment by MatthieuDartiailh** [comment]
I don't know for yum, ...
It should work with pip (I will check). The only thing that may break is the -e option. It does work with python setup.py install/develop (even mixed I tested that locally).

**Comment by MatthieuDartiailh** [comment]
But as zope does that I think it should not be an issue.

**Comment by alexforencich** [comment]
The file `lantz/__init__.py` will not create a conflict if it gets installed to the same location by lantz.core and lantz.drivers?

**Comment by MatthieuDartiailh** [comment]
Installing with pip works (the __init__.py file gets overridden but that is not an issue as there are identical in both repos). Uninstalling might get a bit more messy (it does work but I do not understand why, some cryptic caching stuff).
The issue will be with package manager that does not like a file being owned by two repos. PEP 420 solves this but we can't use it in python 2.
I am not personally super-worried as as long as with stick with pure python I do not see the point of using yum, ....

**Comment by alexforencich** [comment]
Hmm.  Perhaps the simplest option is just to make sure that the **init**.py only exists in one of the packages.  I use Arch Linux and the package manager (pacman) won't install a package if a file is already owned by another package.  However, it would be trivial to add an `rm lantz/__init__.py` to the package step on one of the packages.  We should wait to see if anyone else has any other comments, though.

**Comment by MatthieuDartiailh** [comment]
https://mail.python.org/pipermail/distutils-sig/2015-January/025620.html
Some people actually do see a bunch of issues and actually using pip with -e option crash. And there is a number of talks about virtualenv issues. If only the PEP420 was backported ....

**Comment by MatthieuDartiailh** [comment]
This was perhaps a false good idea, at least as long as we keep python 2 support.

**Comment by alexforencich** [comment]
At any rate, do we really need to support namespace packages? This seems to be primarily intended to pull in packages installed in different locations into the same top-level 'namespace'.  In our case, the packages are most likely going to be installed in the same place, so I'm not sure if the namespace features are required or not.  On the other hand, the namespace setup does allow for relatively easy extensions as separate packages.

**Comment by MatthieuDartiailh** [comment]
Not using namespaces would prevent us to use things like puthon setup.py develop. And firthermpre it would be higly non standard.
We should either keep the existing system or use namespaces bit some ugly mpnster in between.

**Comment by alexforencich** [comment]
True.  It would be nice to use a namespace package, but it's not clear how feasible that is if we want to make it robust and also keep python 2 compatibility.

**Comment by MatthieuDartiailh** [comment]
Given my recent reading I fear it would very britle. So I think I will close this PR.

**Pull request closed without merging**
