### PR TITLE
Add the Action decorator class.

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
Add the Action class to use as a decorator. The class can be easily customized by overriding the decorate method. By default only the units keywords is used and can be specified to use wraps from pint.UnitRegistry if pint is available.
The class must always be instantiate before using it as a decorator ie : 
``` python
@Action()
def test(self):
    pass
```
not 
``` python
@Action
def test(self):
    pass
```

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
On top of units we might want to have a value validations specified as a dictionary (and later a limits validation). I am thinking about that because some command like *SAV can only accept certain values (1, 2, 3, 4) and it would make no sense to have users rewrite the save method just because they want to add validation and a nice error message. We could provide a set_action similar to set_feat to alter an existing action. WDYT ?

**Comment by hgrecco** [comment]
Sounds good to me. I guess we could reuse a lot of the code of the Feat, but we need to specify it by argument

**Comment by MatthieuDartiailh** [comment]
Ready for review @LabPy/owners  ! I will deal with the checks enhancement later.

**Comment by MatthieuDartiailh** [comment]
I looked a bit more at the check enhancement. So either we go the hard way and we do another ast transformer but it will take some time to figure out or we consider pytest an optional dependency and if present we use it to do the job. I am not sure it is worth reinventing the wheel.

**Comment by MatthieuDartiailh** [comment]
@LabPy/owners  has anybody some time to review those changes and #10 ?

**Comment by MatthieuDartiailh** [comment]
I think it might be useful to be able to mark an Action as disabled (raise InvalidAction or such), so that if some basic action is not available for any reason we can make sure the user don't use it and crash the instrument. I am mainly thinking about VisaLibrary functions which are not supported by some instruments. WDYT @LabPy/owners ?

**Comment by MatthieuDartiailh** [comment]
I will leave the invalidation for another PR. In the absence of comment I will merge at the beginning of next week. @hgrecco @alexforencich @arsenovic

**Pull request merged**
