### PR TITLE
Feature method composition

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
I tried to move a bit forward with the implementation of the base Feature class. One thing that was going to be an issue was when we had a lot of things to do at a particular stage as determined by the kwargs. Rebuilding a new function each time would be a mess so I a proposing a composition system. This allows also to decorate specially named method (_post_get, ...) so that they do not override the standard behavior but are rather prepended, appended, or added before or after another operation, this can be quite handy to avoid calling the methods linked to the kwargs by hand. I tried to make it play well with set_feat in the case in which we have some customization using specially named function in some base classes. That part is not pretty but use case for it should be uncommon and strongly discouraged in the docs, I just like the idea that it is possible in some cases.

This is not yet tested but I would appreciate some feedback about those ideas.

When reviewing you can focus on the following modules : 
- features/features.py
- features/util.py
- has_features.py

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Correctly rebased on current master. I will start to add some tests.

**Comment by MatthieuDartiailh** [comment]
The last commit does as indicated some cleanup in how the context manager works and simplifies a bit the metaclass. We could push it further and remove the need for the decorator on methods. But I like the kind of symmetry between feature and actions it brings. Any other opinions ?

**Comment by MatthieuDartiailh** [comment]
This is ready for review. This PR adds the notion of MethodsComposer to the feature and everything linked to handling it and the related tests. The Feature class still lacks the implementation of 'extract' (because the PR is already big enough, and because I am not familiar with the stringparser module from @hgrecco). 
As mentioned earlier, the work in this PR could be used to remove the need for the decorator of methods linked to subsystems, but whether or not to do it is an open question.
The Feature subclasses will be implemented in the next PR.
@LabPy/owners Feel free to ask any question you might have. And take your time for the review. I will start working on the subclasses in the meantime.

**Comment by hgrecco** [comment]
I can add the extract method later. I will say let's wait til monday so that everybody can look at it an if there are no objections we merge it on monday. Ok?

**Comment by MatthieuDartiailh** [comment]
I am fine with that. I won't have time this week to go any further anyway. We can perhaps wait even a little longer as our coworkers might be attending the March meeting. Do you have an opinion on the decarotar issue ?

**Comment by MatthieuDartiailh** [comment]
ping @LabPy/owners

**Comment by MatthieuDartiailh** [comment]
ping @LabPy/owners. It would be nice to make some progress on this.

**Comment by arsenovic** [comment]
i dont even enough time ( or experience really) to review this properly, so please dont wait for my approval on this one.

**Comment by MatthieuDartiailh** [comment]
No problem @arsenovic.

**Comment by MatthieuDartiailh** [comment]
If nobody says no I will merge this weekend.

**Pull request merged**
