### PR TITLE
WIP : Backends VISA

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This adds a PyVISA based backends for instruments. I am pretty happy with it but it is yet untested so not ready to merge.

Please comment and don't forget #2 and #4.

### CODE REVIEW

**Comment by MatthieuDartiailh** [comment]
Rebased on #4 as I need Register.

**Comment by MatthieuDartiailh** [comment]
I am a bit busy so I won't have time to add the missing test any time soon. However if @hgrecco you could review what is already there it would be great. Once this is in we won't be far from being able to start writing drivers !

**Comment by hgrecco** [comment]
it looks good to me. But I think the `assemble_resource_name` can be taken from `pyvisa`. There is something like this already in `pyvisa-sim` and `pyvisa-py` (a parser and formatter of resources that I planned to move to `pyvisa` so that it can be used by all backends)

**Comment by MatthieuDartiailh** [comment]
I would be  ok with this. I will give a look at pyvisa-py and sim and see if I can open a PR in pyvisa. I will then update. Apart from the pendings PR I think we should try to move forward with th standards discussion as it will be the point holding us back quite soon.

**Comment by MatthieuDartiailh** [comment]
I started a new pyvisa branch [ressource_name](https://github.com/MatthieuDartiailh/pyvisa/tree/ressource_names) with a possible approach (this is still heavy WIP). Basically I replaced your parser functions by classes aware of the defaults values of entries and of the canonical string which makes it very easy to assemble a name from a dict (even incomplete). I lack of inspiration with regards of the location and name of that module any ideas ?

**Comment by hgrecco** [comment]
I have another solution based on namedtuples which I like more because they are immutable. I will post it soon to discuss.

**Comment by MatthieuDartiailh** [comment]
Ok let's continue this discussion when you post your code.

**Comment by hgrecco** [comment]
I have created a gist with the code. It passes all the parsing tests from `pyvisa-py`
https://gist.github.com/hgrecco/3c86a4662fd884c67415

**Comment by MatthieuDartiailh** [comment]
I have updated my PR to use the pyvisa.rname module.

**Comment by MatthieuDartiailh** [comment]
A stupid question does anybody knows if there is a difference between using the clear function of VISA and sending *CLS to an instrument ? when both are available what should we do ?

**Comment by alexforencich** [comment]
I think this is instrument-dependent.  I have seen instruments do strange things when sent out-of-band commands (function instead of *whatever).  Not sure if this happens with the clear command, but I have seen strange things with the trigger command.  In theory, they should be interchangeable, but this does not appear to be the case.

**Comment by MatthieuDartiailh** [comment]
Nice mess ! Should we then always use the *MSG instead of visa function when available ? (save perhaps for the status_byte, I secretly hope that serial polling is more effective than sending *STB?)
The question pops up because I am currently implementing the IEEE standards (*IDN and friends) and wondering whether to override the methods I implemented in the BaseVisaDriver relying on library functions.

**Comment by MatthieuDartiailh** [comment]
I rebased on #12 for convenience.

**Comment by MatthieuDartiailh** [comment]
This is not completely polished but it is usable. I propose we merge it as is and improve it later.

**Comment by alexforencich** [comment]
I am trying to get started working on some drivers, but I have not been able to get this to work.  Do you have some basic example code for how to instantiate a driver using this backend?

**Comment by MatthieuDartiailh** [comment]
Sorry I fixed a bug yesterday and forgot to push. (I may have fixed on another computer in June but forgot to grab the change)

Here is the way to go to start a start a driver : 
```python

# Using directly the resource_name
driver = MyDriver(dict(resource_name='TCPIP::192.168.0.10::INSTR'))
driver.initialize()

# Letting pyvisa build the resource name
anc = ANC300(connection_infos=dict(host_address='192.168.0.100', interface_type='TCPIP', 
                                   resource_class='SOCKET', port=7230, backend='@py'))
anc.initialize()

# Using the via_tcpip_socket works also:
anc = ANC300.via_tcpip_socket(host_address='192.168.0.100', port=7230)

```
For me the backend works but I fail to get pyvisa-py to work (get an unset library, using lantz or directly using pyvisa).

I hope to find some time to work on adding the much needed tests in the coming days. Anyway do not hesitate if you have more questions.

**Comment by MatthieuDartiailh** [comment]
Actually backend kwargs was ignored in via_ methods this is fixed now.

**Comment by alexforencich** [comment]
Why a dict and not kwargs?

**Comment by alexforencich** [comment]
And what's the issue with pyvisa-py?  I don't have NI VISA installed, so that's the only backend that I can use.  How is backend selection supposed to work?

**Comment by hgrecco** [comment]
Regarding the backend, I have a few proposals. First is that we use a global setting or environmental variable to tell Lantz which backend we want. Doing this in a single place is convenient.

Additionally, we chose the `@` symbol to specify the meaning, not only due to its meaning but because it is also not usually found in resource names. Therefore the plan is that you can say `'TCPIP::192.168.0.10::INSTR@py'` and PyVISA will dispatch internally to the PyVISA-py backend.

I am testing this right now, having real and simulated instruments together in one script. I will push it to pyvisa as soon as it is stable.

**Comment by arsenovic** [comment]
my two cents: i like the environmental variable ability

**Comment by MatthieuDartiailh** [comment]
Initially there were more arguments to the constructor (we cut that number down at the beginning of our discussions), hence the dictionary. We could probably go to use only **kwargs now. Is @alexforencich point of view shared by the others ?

Backend selection works as the tests (which are not yet run on travis) do use the pyvisa-sim backend. However on my personal computer, pyvisa-py does not work but I don't have to investigate right now.

@hgrecco just to clarify the discussion I consider Visa a backend no matter the selected resource manager. A system using direct call to a dll would be another backend. That being said one can already set the resource manager used by Lantz using the **set_visa_resource_manager** function. For the time being the default backend is '@ni' and saved under that id. I will change this so that Lantz used by default the ResourceManager stored under the *default* id.
Any idea about the name to give to the environment variable ?

**Comment by alexforencich** [comment]
Using a dict like that is not very clean. If you can do that with kwargs, that would be better. It would be even better if it can figure out a bare resource string alone as a single positional argument, if that doesn't cause any major issues.

**Comment by MatthieuDartiailh** [comment]
I will try to allow the single positional arg, I should be able to make the driver unicity support it.

**Comment by MatthieuDartiailh** [comment]
The last two commits should basically address all remarks so far. I also opened a PR on pyvisa-py to get the TCPIP working again (import issue, https://github.com/hgrecco/pyvisa-py/pull/51). I will add the test for the backend to travis now.

**Comment by hgrecco** [comment]
@MatthieuDartiailh I completely agree about the backend. That is also my view. I like the `set_visa_resource_manager` and I think we should keep it. The question is if people will rather have a way to define what is the default (Instead of saying in every script  `set_visa_resource_manager('@py')`).

I see a few different ways:
1. Use PyVISA : By changing the library path variable in `.pyvisarc` you can change the default backend. We can leave lantz default with no backend, which means use PyVISA default. 
2. Have a lantz configuration file (In my opinion this only makes sense if we have to store something else).
3. Have an OS environment variable.

Just to be clear, in any of the three cases `set_visa_resource_manager` is still available.

(By the way, I am going to open a ticket in pyvisa regarding the location of the pyvisarc file as I think we are doing it wrong. We should follow something along these lines: http://click.pocoo.org/4/api/#click.get_app_dir to make it really cross platform)

**Comment by alexforencich** [comment]
How is the PROTOCOLS dict supposed to be used in the driver?  Is this just informational?  Does anything need to be done with respect to things like GPIB to LAN bridges?  Maybe this is more of a probem with pyvisa-py than with pyvisa, as NI-VISA allows you to add remote GPIB to LAN boxes as GPIB interfaces.

**Comment by alexforencich** [comment]
Also, what about 'fallback' backends?  Say, if @ni is not available due to missing NI-VISA, automatically fall back on @py.

**Comment by hgrecco** [comment]
@alexforencich This is a good point. We should look into this. Maybe allowing a list of backends?

**Comment by alexforencich** [comment]
Yeah, that could be a good idea.  Try the first one, fall back down the list if backends can't be loaded.  Perhaps even autodetect pyvisa-py and set the default list to include that as the fallback automatically.

**Comment by alexforencich** [comment]
Just wondering, why is there a via_usb and a _via_usb method?  Is one of these more than just an alias?

**Comment by hgrecco** [comment]
via_usb and via_usb_raw share a large amount of code which is in _via_usb

**Comment by alexforencich** [comment]
Ah, for some reason I didn't see via_usb_raw.

**Comment by arsenovic** [comment]
generically comments.

 its nice to init an object as concisely as possible, while retaining the ability to fully specify all options. i know that `pandas.DataFrame` has many `@classmethod`  initializers like `from_string` or `from_dict`, and these are all called  in the __init__,  based on the input kwarg type, or in a series of try/excepts.

i can see two use cases, where constructing a instrument from an API-like interface would want to use a dict, but a user would want to just use a string. 

also with regard to the backend; i suspect most users will just want it 'to work', so detection of backend or try/excepts  would be a good default behavior.

**Comment by MatthieuDartiailh** [comment]
Every time lantz needs a resource manager it goes through the get_visa_resource_manager function. So any fallback backend could go there. I added an env var LANTZ _VISA. I am open to other solutions. I am moving out of my flat in the next few days so don't expect any major updates.
The PROTOCOLES (I will fix the spelling) is used to complete partial informations provided as keywords (you can specify that TCPIP use socket on port 5555 and simply say you want TCPIP connection to host_address xxx.xxx.xxx.xxx. For the time being there is no bridge support but this is a pyvisa thing.

**Comment by alexforencich** [comment]
Well, my point with bridges is that a GPIB-only device sitting behind a bridge 'becomes' a TCPIP device from the standpoint of pyvisa when sitting behind a GPIB-LAN bridge (well, unless NI-VISA maps the bridge to look like a local GPIB device) and this protocols array does not seem to explicitly support this.  I'm not saying anything needs to be changed necessarily, just that the drivers need to be constructed in such a way that a driver for a GPIB-only instrument will work correctly through a GPIB-LAN bridge.

**Comment by alexforencich** [comment]
One other thing to consider w.r.t. things 'just working' is possibly bundling pyvisa-py into pyvisa so that pyvisa can automatically fall back on the python-based interfaces when NI-VISA is not present.

**Comment by alexforencich** [comment]
You need a check 'if backend not in _RESOURCE_MANAGERS' in get_visa_resource_manager so you don't overwrite a resource manager that has been set already.  Also, I like your choice of variable name for the log message.

**Comment by MatthieuDartiailh** [comment]
I will fix it asap (beginning of august is the most likely) I just went too fast in my last refactoring.

**Comment by MatthieuDartiailh** [comment]
Thanks for pointing it out !

**Comment by MatthieuDartiailh** [comment]
Comment addressed. I will try to see if I can get some tests for via_usb now that pyvisa sim supports filter.

**Comment by MatthieuDartiailh** [comment]
Ok I added the tests for via_usb.

One question @hgrecco is the query method of pyvisa thread-safe ? If not we might consider locking while calling when we expose it in Lantz.

**Comment by hgrecco** [comment]
PyVISA is thread safe since version 1.6

**Comment by MatthieuDartiailh** [comment]
@hgrecco Could you point me to the part of the code that makes it so ? Looking at the current code it seems to me that the GIL can be released in the low level of the library write method and allow to another thread to issue a write. Such a situation might cause trouble in some cases.

**Comment by hgrecco** [comment]
I am not following you. Considering that NI-VISA is thread safe, what type of trouble you are considering?

**Comment by MatthieuDartiailh** [comment]
I am considering two threads attempting to query some values from the same instruments. In the absence of a lock during the query preventing thread switching between the write and read operation the data can end up being read by the wrong thread. Hence my proposal to perform query behind a lock in Lantz.

**Comment by hgrecco** [comment]
I see. PyVISA is thread safe in the same way the NI-VISA is. You can query N instrument in N threads without a problem, but you should not mix. If you operate in different threads with the same instrument you should implement your own locks. I am fine with adding lock in Lantz, but I think that we should keep PyVISA closer to NI-VISA.

**Comment by MatthieuDartiailh** [comment]
I have no problem with keeping py-visa the way it is, I just wanted to know whether it made sense to use the lock (that we already have for each instrument) in a Lantz query. I will add the additional code to the query functions in Lantz.

**Comment by alexforencich** [comment]
It would be nice to get this merged soon to make the main branch of lantz_core actually more or less usable for controlling instruments and developing drivers.  Is there anything else major that needs to be done here, aside from fixing the coverage?

**Comment by MatthieuDartiailh** [comment]
I will add the discussed thread safety to query today. I will also try to add some tests for increasing a bit more the coverage but basically the lack of coverage comes from not being able to test all pyvisa wrapped function because pyvisa-sim lacks some of them. But this should not hold back the merge. Once my last commits are in today I will merge.

**Pull request merged**
