### PR TITLE
Features : Mapping, Bool, Unicode, Int, Float

### PR DESCRIPTION
**Pull request by MatthieuDartiailh**
This is based on #2 so don't merge before #2.

Add all the basic features found in Eapii. This is close to what I did in Eapii so feel free to comment I don't want to impose my way.
- Mapping : support mapping a user value to an instrument value is back
- Bool : Mapping(for True, False) + support aliases allowing to pass 'On' instead of True (NB the answer is always True never 'On')
- Unicode : simple feature for string like objects, support set of allowed values
- Int : support set of allowed values or limits (either fix or by ID, ie a limit is declared by writting a _limits_* methods full support for this new construct has been added)
- Float same as Int and support for unit (this is not mandatory and can work without Pint, we can also add an option so that even if unit supports is available the returned value will be a float). For the time being the value is always returned in the same unit, we could add more options.
I tried to keep each commit quite focused so doing the revision commit by commit should be 'easy'.

### CODE REVIEW

**Comment by hgrecco** [comment]
Let's try to merge the other PR and this by next week so we can move forward

**Comment by MatthieuDartiailh** [comment]
It is fine with me. I will also prepare a PR with the PyVisa backend if I find some more time.

**Comment by hgrecco** [comment]
Look at the Lantz MessageBasedDriver.

**Comment by MatthieuDartiailh** [comment]
I was planning to. I will try to take the best of it and the Eapii MessageBasedDriver.

**Comment by MatthieuDartiailh** [comment]
ping @LabPy/owners

**Comment by arsenovic** [comment]
i just read your commit comments, 

is the Unicode type a combination of String  and Enum?
is there any type for lists? 

i also deal a lot with complex arrays, but i dont think this is a common usage.

**Comment by MatthieuDartiailh** [comment]
It is a subclass of the base enumerable feature indeed. There is no String Feature, but we could have a Byte Feature perhaps. I prefer to enforce the bytes/unicode as it is likely to bite people when going from 2 to 3.
For arrays I don't think we need it as I guess that those arrays are mostly read-only (measure of a PNA or spectrum analyser) or do you have a use case where having a Feature for getting/setting an array make sense ?

**Comment by arsenovic** [comment]
so, here is an example for get/set calibration coefficients  for a vna where an array/list might be appropriate.
https://github.com/scikit-rf/scikit-rf/blob/master/skrf/vi/vna.py#L1278-L1327

that example is a actually is a dict of arrays, and you can see i have to translate to and from a comma seperated string. i could see a List type being used for get/set frequency-dependent data (like for importing data ->memory), which you might want on a SpecAnalyzer too

 a common data flow for a VNA  would be:
complex array -> real tuple array -> string -> VNA 
then backwards.

certain things make sense to form higher objects to, like multiport s-parameters  are effectively sets of complex arrays, to the above data flow would have an additional layer at the front.

**Comment by MatthieuDartiailh** [comment]
Interesting I never used that on my PNA (but we do only very basic measures). The only thing I worry a bit about is the re-usability of the Array/List Feature as the conversion is most likely to be very specific to the instrument. I will have to think more about this one. But anyway we should address this in a subsequent PR I think.

**Comment by alexforencich** [comment]
It's also possible to implement something like that with getters and setters.  Not sure what makes the most sense.  I agree that we should open an new issue/PR for it, though.

**Comment by MatthieuDartiailh** [comment]
We can always start from a raw Feature and do what we want so we keep a Feature for consistency.

**Comment by arsenovic** [comment]
sounds good

**Comment by MatthieuDartiailh** [comment]
Note : this requires the current development version of Pint

**Comment by MatthieuDartiailh** [comment]
I will merge it this week-end if nobody says no. I will also open an issue for the Array Feature.

**Pull request merged**
